<?php

/**
 * @file
 * Enables multi-user blogs.
 */

/**
 * Implements hook_node_info().
 */
function myct_node_info() {
  return array(
    'myct' => array(
      'name' => t('Blog entry'),
      'base' => 'node_content',
      'custom' => 1,
      'modified' => 1,
      'locked' => 0,
      'has_title' => TRUE,
      'description' => t('Use for multi-user blogs. Every user gets a personal blog.'),
      'title_label' => t('Имя Фамилия'),
    )
  );
}

function myct_form($node, &$form_state) {

$form = array();

  $form['my_value'] = array(
    '#type' => 'textfield',
    'title' => t('Some title'),
    '#default_value' => isset($node->my_value) ? $node->my_value : '',
  );
  return $form;


}

